// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefBrowserHost extends Structure{
public CefBrowserHost(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface GetBrowserFunc extends Callback {

CefBrowser get_browser(CefBrowserHost x0); 
}

public static interface CloseBrowserFunc extends Callback {

void close_browser(CefBrowserHost x0, int x1); 
}

public static interface TryCloseBrowserFunc extends Callback {

int try_close_browser(CefBrowserHost x0); 
}

public static interface SetFocusFunc extends Callback {

void set_focus(CefBrowserHost x0, int x1); 
}

public static interface GetWindowHandleFunc extends Callback {

Pointer get_window_handle(CefBrowserHost x0); 
}

public static interface GetOpenerWindowHandleFunc extends Callback {

Pointer get_opener_window_handle(CefBrowserHost x0); 
}

public static interface HasViewFunc extends Callback {

int has_view(CefBrowserHost x0); 
}

public static interface GetClientFunc extends Callback {

CefClient get_client(CefBrowserHost x0); 
}

public static interface GetRequestContextFunc extends Callback {

CefRequestContext get_request_context(CefBrowserHost x0); 
}

public static interface GetZoomLevelFunc extends Callback {

double get_zoom_level(CefBrowserHost x0); 
}

public static interface SetZoomLevelFunc extends Callback {

void set_zoom_level(CefBrowserHost x0, double x1); 
}

public static interface RunFileDialogFunc extends Callback {

void run_file_dialog(CefBrowserHost x0, int x1, CefStringUtf16 x2, CefStringUtf16 x3, Pointer x4, int x5, CefRunFileDialogCallback x6); 
}

public static interface StartDownloadFunc extends Callback {

void start_download(CefBrowserHost x0, CefStringUtf16 x1); 
}

public static interface DownloadImageFunc extends Callback {

void download_image(CefBrowserHost x0, CefStringUtf16 x1, int x2, int x3, int x4, CefDownloadImageCallback x5); 
}

public static interface PrintFunc extends Callback {

void print(CefBrowserHost x0); 
}

public static interface PrintToPdfFunc extends Callback {

void print_to_pdf(CefBrowserHost x0, CefStringUtf16 x1, CefPdfPrintSettings x2, CefPdfPrintCallback x3); 
}

public static interface FindFunc extends Callback {

void find(CefBrowserHost x0, int x1, CefStringUtf16 x2, int x3, int x4, int x5); 
}

public static interface StopFindingFunc extends Callback {

void stop_finding(CefBrowserHost x0, int x1); 
}

public static interface ShowDevToolsFunc extends Callback {

void show_dev_tools(CefBrowserHost x0, Pointer x1, CefClient x2, CefBrowserSettings x3, CefPoint x4); 
}

public static interface CloseDevToolsFunc extends Callback {

void close_dev_tools(CefBrowserHost x0); 
}

public static interface HasDevToolsFunc extends Callback {

int has_dev_tools(CefBrowserHost x0); 
}

public static interface SendDevToolsMessageFunc extends Callback {

int send_dev_tools_message(CefBrowserHost x0, Pointer x1, SizeT x2); 
}

public static interface ExecuteDevToolsMethodFunc extends Callback {

int execute_dev_tools_method(CefBrowserHost x0, int x1, CefStringUtf16 x2, CefDictionaryValue x3); 
}

public static interface AddDevToolsMessageObserverFunc extends Callback {

CefRegistration add_dev_tools_message_observer(CefBrowserHost x0, CefDevToolsMessageObserver x1); 
}

public static interface GetNavigationEntriesFunc extends Callback {

void get_navigation_entries(CefBrowserHost x0, CefNavigationEntryVisitor x1, int x2); 
}

public static interface ReplaceMisspellingFunc extends Callback {

void replace_misspelling(CefBrowserHost x0, CefStringUtf16 x1); 
}

public static interface AddWordToDictionaryFunc extends Callback {

void add_word_to_dictionary(CefBrowserHost x0, CefStringUtf16 x1); 
}

public static interface IsWindowRenderingDisabledFunc extends Callback {

int is_window_rendering_disabled(CefBrowserHost x0); 
}

public static interface WasResizedFunc extends Callback {

void was_resized(CefBrowserHost x0); 
}

public static interface WasHiddenFunc extends Callback {

void was_hidden(CefBrowserHost x0, int x1); 
}

public static interface NotifyScreenInfoChangedFunc extends Callback {

void notify_screen_info_changed(CefBrowserHost x0); 
}

public static interface InvalidateFunc extends Callback {

void invalidate(CefBrowserHost x0, int x1); 
}

public static interface SendExternalBeginFrameFunc extends Callback {

void send_external_begin_frame(CefBrowserHost x0); 
}

public static interface SendKeyEventFunc extends Callback {

void send_key_event(CefBrowserHost x0, CefKeyEvent x1); 
}

public static interface SendMouseClickEventFunc extends Callback {

void send_mouse_click_event(CefBrowserHost x0, CefMouseEvent x1, int x2, int x3, int x4); 
}

public static interface SendMouseMoveEventFunc extends Callback {

void send_mouse_move_event(CefBrowserHost x0, CefMouseEvent x1, int x2); 
}

public static interface SendMouseWheelEventFunc extends Callback {

void send_mouse_wheel_event(CefBrowserHost x0, CefMouseEvent x1, int x2, int x3); 
}

public static interface SendTouchEventFunc extends Callback {

void send_touch_event(CefBrowserHost x0, CefTouchEvent x1); 
}

public static interface SendFocusEventFunc extends Callback {

void send_focus_event(CefBrowserHost x0, int x1); 
}

public static interface SendCaptureLostEventFunc extends Callback {

void send_capture_lost_event(CefBrowserHost x0); 
}

public static interface NotifyMoveOrResizeStartedFunc extends Callback {

void notify_move_or_resize_started(CefBrowserHost x0); 
}

public static interface GetWindowlessFrameRateFunc extends Callback {

int get_windowless_frame_rate(CefBrowserHost x0); 
}

public static interface SetWindowlessFrameRateFunc extends Callback {

void set_windowless_frame_rate(CefBrowserHost x0, int x1); 
}

public static interface ImeSetCompositionFunc extends Callback {

void ime_set_composition(CefBrowserHost x0, CefStringUtf16 x1, SizeT x2, CefCompositionUnderline x3, CefRange x4, CefRange x5); 
}

public static interface ImeCommitTextFunc extends Callback {

void ime_commit_text(CefBrowserHost x0, CefStringUtf16 x1, CefRange x2, int x3); 
}

public static interface ImeFinishComposingTextFunc extends Callback {

void ime_finish_composing_text(CefBrowserHost x0, int x1); 
}

public static interface ImeCancelCompositionFunc extends Callback {

void ime_cancel_composition(CefBrowserHost x0); 
}

public static interface DragTargetDragEnterFunc extends Callback {

void drag_target_drag_enter(CefBrowserHost x0, CefDragData x1, CefMouseEvent x2, int x3); 
}

public static interface DragTargetDragOverFunc extends Callback {

void drag_target_drag_over(CefBrowserHost x0, CefMouseEvent x1, int x2); 
}

public static interface DragTargetDragLeaveFunc extends Callback {

void drag_target_drag_leave(CefBrowserHost x0); 
}

public static interface DragTargetDropFunc extends Callback {

void drag_target_drop(CefBrowserHost x0, CefMouseEvent x1); 
}

public static interface DragSourceEndedAtFunc extends Callback {

void drag_source_ended_at(CefBrowserHost x0, int x1, int x2, int x3); 
}

public static interface DragSourceSystemDragEndedFunc extends Callback {

void drag_source_system_drag_ended(CefBrowserHost x0); 
}

public static interface GetVisibleNavigationEntryFunc extends Callback {

CefNavigationEntry get_visible_navigation_entry(CefBrowserHost x0); 
}

public static interface SetAccessibilityStateFunc extends Callback {

void set_accessibility_state(CefBrowserHost x0, int x1); 
}

public static interface SetAutoResizeEnabledFunc extends Callback {

void set_auto_resize_enabled(CefBrowserHost x0, int x1, CefSize x2, CefSize x3); 
}

public static interface GetExtensionFunc extends Callback {

CefExtension get_extension(CefBrowserHost x0); 
}

public static interface IsBackgroundHostFunc extends Callback {

int is_background_host(CefBrowserHost x0); 
}

public static interface SetAudioMutedFunc extends Callback {

void set_audio_muted(CefBrowserHost x0, int x1); 
}

public static interface IsAudioMutedFunc extends Callback {

int is_audio_muted(CefBrowserHost x0); 
}

public CefBaseRefCounted base;

public GetBrowserFunc get_browser;

public CloseBrowserFunc close_browser;

public TryCloseBrowserFunc try_close_browser;

public SetFocusFunc set_focus;

public GetWindowHandleFunc get_window_handle;

public GetOpenerWindowHandleFunc get_opener_window_handle;

public HasViewFunc has_view;

public GetClientFunc get_client;

public GetRequestContextFunc get_request_context;

public GetZoomLevelFunc get_zoom_level;

public SetZoomLevelFunc set_zoom_level;

public RunFileDialogFunc run_file_dialog;

public StartDownloadFunc start_download;

public DownloadImageFunc download_image;

public PrintFunc print;

public PrintToPdfFunc print_to_pdf;

public FindFunc find;

public StopFindingFunc stop_finding;

public ShowDevToolsFunc show_dev_tools;

public CloseDevToolsFunc close_dev_tools;

public HasDevToolsFunc has_dev_tools;

public SendDevToolsMessageFunc send_dev_tools_message;

public ExecuteDevToolsMethodFunc execute_dev_tools_method;

public AddDevToolsMessageObserverFunc add_dev_tools_message_observer;

public GetNavigationEntriesFunc get_navigation_entries;

public ReplaceMisspellingFunc replace_misspelling;

public AddWordToDictionaryFunc add_word_to_dictionary;

public IsWindowRenderingDisabledFunc is_window_rendering_disabled;

public WasResizedFunc was_resized;

public WasHiddenFunc was_hidden;

public NotifyScreenInfoChangedFunc notify_screen_info_changed;

public InvalidateFunc invalidate;

public SendExternalBeginFrameFunc send_external_begin_frame;

public SendKeyEventFunc send_key_event;

public SendMouseClickEventFunc send_mouse_click_event;

public SendMouseMoveEventFunc send_mouse_move_event;

public SendMouseWheelEventFunc send_mouse_wheel_event;

public SendTouchEventFunc send_touch_event;

public SendFocusEventFunc send_focus_event;

public SendCaptureLostEventFunc send_capture_lost_event;

public NotifyMoveOrResizeStartedFunc notify_move_or_resize_started;

public GetWindowlessFrameRateFunc get_windowless_frame_rate;

public SetWindowlessFrameRateFunc set_windowless_frame_rate;

public ImeSetCompositionFunc ime_set_composition;

public ImeCommitTextFunc ime_commit_text;

public ImeFinishComposingTextFunc ime_finish_composing_text;

public ImeCancelCompositionFunc ime_cancel_composition;

public DragTargetDragEnterFunc drag_target_drag_enter;

public DragTargetDragOverFunc drag_target_drag_over;

public DragTargetDragLeaveFunc drag_target_drag_leave;

public DragTargetDropFunc drag_target_drop;

public DragSourceEndedAtFunc drag_source_ended_at;

public DragSourceSystemDragEndedFunc drag_source_system_drag_ended;

public GetVisibleNavigationEntryFunc get_visible_navigation_entry;

public SetAccessibilityStateFunc set_accessibility_state;

public SetAutoResizeEnabledFunc set_auto_resize_enabled;

public GetExtensionFunc get_extension;

public IsBackgroundHostFunc is_background_host;

public SetAudioMutedFunc set_audio_muted;

public IsAudioMutedFunc is_audio_muted;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "get_browser", "close_browser", "try_close_browser", "set_focus", "get_window_handle", "get_opener_window_handle", "has_view", "get_client", "get_request_context", "get_zoom_level", "set_zoom_level", "run_file_dialog", "start_download", "download_image", "print", "print_to_pdf", "find", "stop_finding", "show_dev_tools", "close_dev_tools", "has_dev_tools", "send_dev_tools_message", "execute_dev_tools_method", "add_dev_tools_message_observer", "get_navigation_entries", "replace_misspelling", "add_word_to_dictionary", "is_window_rendering_disabled", "was_resized", "was_hidden", "notify_screen_info_changed", "invalidate", "send_external_begin_frame", "send_key_event", "send_mouse_click_event", "send_mouse_move_event", "send_mouse_wheel_event", "send_touch_event", "send_focus_event", "send_capture_lost_event", "notify_move_or_resize_started", "get_windowless_frame_rate", "set_windowless_frame_rate", "ime_set_composition", "ime_commit_text", "ime_finish_composing_text", "ime_cancel_composition", "drag_target_drag_enter", "drag_target_drag_over", "drag_target_drag_leave", "drag_target_drop", "drag_source_ended_at", "drag_source_system_drag_ended", "get_visible_navigation_entry", "set_accessibility_state", "set_auto_resize_enabled", "get_extension", "is_background_host", "set_audio_muted", "is_audio_muted");
 }

public CefBrowser getBrowser () {

return  this.get_browser.get_browser(this);

}

public void closeBrowser (int x1) {

  this.close_browser.close_browser(this,  x1);

}

public int tryCloseBrowser () {

return  this.try_close_browser.try_close_browser(this);

}

public void setFocus (int x1) {

  this.set_focus.set_focus(this,  x1);

}

public Pointer getWindowHandle () {

return  this.get_window_handle.get_window_handle(this);

}

public Pointer getOpenerWindowHandle () {

return  this.get_opener_window_handle.get_opener_window_handle(this);

}

public int hasView () {

return  this.has_view.has_view(this);

}

public CefClient getClient () {

return  this.get_client.get_client(this);

}

public CefRequestContext getRequestContext () {

return  this.get_request_context.get_request_context(this);

}

public double getZoomLevel () {

return  this.get_zoom_level.get_zoom_level(this);

}

public void setZoomLevel (double x1) {

  this.set_zoom_level.set_zoom_level(this,  x1);

}

public void runFileDialog (int x1, String x2, String x3, Pointer x4, int x5, CefRunFileDialogCallback x6) {

  this.run_file_dialog.run_file_dialog(this,  x1, CljCefLib.toCefString(x2), CljCefLib.toCefString(x3),  x4,  x5,  x6);

}

public void startDownload (String x1) {

  this.start_download.start_download(this, CljCefLib.toCefString(x1));

}

public void downloadImage (String x1, int x2, int x3, int x4, CefDownloadImageCallback x5) {

  this.download_image.download_image(this, CljCefLib.toCefString(x1),  x2,  x3,  x4,  x5);

}

public void print () {

  this.print.print(this);

}

public void printToPdf (String x1, CefPdfPrintSettings x2, CefPdfPrintCallback x3) {

  this.print_to_pdf.print_to_pdf(this, CljCefLib.toCefString(x1),  x2,  x3);

}

public void find (int x1, String x2, int x3, int x4, int x5) {

  this.find.find(this,  x1, CljCefLib.toCefString(x2),  x3,  x4,  x5);

}

public void stopFinding (int x1) {

  this.stop_finding.stop_finding(this,  x1);

}

public void showDevTools (Pointer x1, CefClient x2, CefBrowserSettings x3, CefPoint x4) {

  this.show_dev_tools.show_dev_tools(this,  x1,  x2,  x3,  x4);

}

public void closeDevTools () {

  this.close_dev_tools.close_dev_tools(this);

}

public int hasDevTools () {

return  this.has_dev_tools.has_dev_tools(this);

}

public int sendDevToolsMessage (Pointer x1, SizeT x2) {

return  this.send_dev_tools_message.send_dev_tools_message(this,  x1,  x2);

}

public int executeDevToolsMethod (int x1, String x2, CefDictionaryValue x3) {

return  this.execute_dev_tools_method.execute_dev_tools_method(this,  x1, CljCefLib.toCefString(x2),  x3);

}

public CefRegistration addDevToolsMessageObserver (CefDevToolsMessageObserver x1) {

return  this.add_dev_tools_message_observer.add_dev_tools_message_observer(this,  x1);

}

public void getNavigationEntries (CefNavigationEntryVisitor x1, int x2) {

  this.get_navigation_entries.get_navigation_entries(this,  x1,  x2);

}

public void replaceMisspelling (String x1) {

  this.replace_misspelling.replace_misspelling(this, CljCefLib.toCefString(x1));

}

public void addWordToDictionary (String x1) {

  this.add_word_to_dictionary.add_word_to_dictionary(this, CljCefLib.toCefString(x1));

}

public int isWindowRenderingDisabled () {

return  this.is_window_rendering_disabled.is_window_rendering_disabled(this);

}

public void wasResized () {

  this.was_resized.was_resized(this);

}

public void wasHidden (int x1) {

  this.was_hidden.was_hidden(this,  x1);

}

public void notifyScreenInfoChanged () {

  this.notify_screen_info_changed.notify_screen_info_changed(this);

}

public void invalidate (int x1) {

  this.invalidate.invalidate(this,  x1);

}

public void sendExternalBeginFrame () {

  this.send_external_begin_frame.send_external_begin_frame(this);

}

public void sendKeyEvent (CefKeyEvent x1) {

  this.send_key_event.send_key_event(this,  x1);

}

public void sendMouseClickEvent (CefMouseEvent x1, int x2, int x3, int x4) {

  this.send_mouse_click_event.send_mouse_click_event(this,  x1,  x2,  x3,  x4);

}

public void sendMouseMoveEvent (CefMouseEvent x1, int x2) {

  this.send_mouse_move_event.send_mouse_move_event(this,  x1,  x2);

}

public void sendMouseWheelEvent (CefMouseEvent x1, int x2, int x3) {

  this.send_mouse_wheel_event.send_mouse_wheel_event(this,  x1,  x2,  x3);

}

public void sendTouchEvent (CefTouchEvent x1) {

  this.send_touch_event.send_touch_event(this,  x1);

}

public void sendFocusEvent (int x1) {

  this.send_focus_event.send_focus_event(this,  x1);

}

public void sendCaptureLostEvent () {

  this.send_capture_lost_event.send_capture_lost_event(this);

}

public void notifyMoveOrResizeStarted () {

  this.notify_move_or_resize_started.notify_move_or_resize_started(this);

}

public int getWindowlessFrameRate () {

return  this.get_windowless_frame_rate.get_windowless_frame_rate(this);

}

public void setWindowlessFrameRate (int x1) {

  this.set_windowless_frame_rate.set_windowless_frame_rate(this,  x1);

}

public void imeSetComposition (String x1, SizeT x2, CefCompositionUnderline x3, CefRange x4, CefRange x5) {

  this.ime_set_composition.ime_set_composition(this, CljCefLib.toCefString(x1),  x2,  x3,  x4,  x5);

}

public void imeCommitText (String x1, CefRange x2, int x3) {

  this.ime_commit_text.ime_commit_text(this, CljCefLib.toCefString(x1),  x2,  x3);

}

public void imeFinishComposingText (int x1) {

  this.ime_finish_composing_text.ime_finish_composing_text(this,  x1);

}

public void imeCancelComposition () {

  this.ime_cancel_composition.ime_cancel_composition(this);

}

public void dragTargetDragEnter (CefDragData x1, CefMouseEvent x2, int x3) {

  this.drag_target_drag_enter.drag_target_drag_enter(this,  x1,  x2,  x3);

}

public void dragTargetDragOver (CefMouseEvent x1, int x2) {

  this.drag_target_drag_over.drag_target_drag_over(this,  x1,  x2);

}

public void dragTargetDragLeave () {

  this.drag_target_drag_leave.drag_target_drag_leave(this);

}

public void dragTargetDrop (CefMouseEvent x1) {

  this.drag_target_drop.drag_target_drop(this,  x1);

}

public void dragSourceEndedAt (int x1, int x2, int x3) {

  this.drag_source_ended_at.drag_source_ended_at(this,  x1,  x2,  x3);

}

public void dragSourceSystemDragEnded () {

  this.drag_source_system_drag_ended.drag_source_system_drag_ended(this);

}

public CefNavigationEntry getVisibleNavigationEntry () {

return  this.get_visible_navigation_entry.get_visible_navigation_entry(this);

}

public void setAccessibilityState (int x1) {

  this.set_accessibility_state.set_accessibility_state(this,  x1);

}

public void setAutoResizeEnabled (int x1, CefSize x2, CefSize x3) {

  this.set_auto_resize_enabled.set_auto_resize_enabled(this,  x1,  x2,  x3);

}

public CefExtension getExtension () {

return  this.get_extension.get_extension(this);

}

public int isBackgroundHost () {

return  this.is_background_host.is_background_host(this);

}

public void setAudioMuted (int x1) {

  this.set_audio_muted.set_audio_muted(this,  x1);

}

public int isAudioMuted () {

return  this.is_audio_muted.is_audio_muted(this);

}}