// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefBrowserProcessHandler extends Structure{
public CefBrowserProcessHandler(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface GetCookieableSchemesFunc extends Callback {

void get_cookieable_schemes(CefBrowserProcessHandler x0, Pointer x1, Pointer x2); 
}

public static interface OnContextInitializedFunc extends Callback {

void on_context_initialized(CefBrowserProcessHandler x0); 
}

public static interface OnBeforeChildProcessLaunchFunc extends Callback {

void on_before_child_process_launch(CefBrowserProcessHandler x0, CefCommandLine x1); 
}

public static interface GetPrintHandlerFunc extends Callback {

CefPrintHandler get_print_handler(CefBrowserProcessHandler x0); 
}

public static interface OnScheduleMessagePumpWorkFunc extends Callback {

void on_schedule_message_pump_work(CefBrowserProcessHandler x0, long x1); 
}

public static interface GetDefaultClientFunc extends Callback {

CefClient get_default_client(CefBrowserProcessHandler x0); 
}

public CefBaseRefCounted base;

public GetCookieableSchemesFunc get_cookieable_schemes;

public OnContextInitializedFunc on_context_initialized;

public OnBeforeChildProcessLaunchFunc on_before_child_process_launch;

public GetPrintHandlerFunc get_print_handler;

public OnScheduleMessagePumpWorkFunc on_schedule_message_pump_work;

public GetDefaultClientFunc get_default_client;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "get_cookieable_schemes", "on_context_initialized", "on_before_child_process_launch", "get_print_handler", "on_schedule_message_pump_work", "get_default_client");
 }

public void getCookieableSchemes (Pointer x1, Pointer x2) {

  this.get_cookieable_schemes.get_cookieable_schemes(this,  x1,  x2);

}

public void onContextInitialized () {

  this.on_context_initialized.on_context_initialized(this);

}

public void onBeforeChildProcessLaunch (CefCommandLine x1) {

  this.on_before_child_process_launch.on_before_child_process_launch(this,  x1);

}

public CefPrintHandler getPrintHandler () {

return  this.get_print_handler.get_print_handler(this);

}

public void onScheduleMessagePumpWork (long x1) {

  this.on_schedule_message_pump_work.on_schedule_message_pump_work(this,  x1);

}

public CefClient getDefaultClient () {

return  this.get_default_client.get_default_client(this);

}}