// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefCookieManager extends Structure{
public CefCookieManager(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface SetSupportedSchemesFunc extends Callback {

void set_supported_schemes(CefCookieManager x0, Pointer x1, int x2, CefCompletionCallback x3); 
}

public static interface VisitAllCookiesFunc extends Callback {

int visit_all_cookies(CefCookieManager x0, CefCookieVisitor x1); 
}

public static interface VisitUrlCookiesFunc extends Callback {

int visit_url_cookies(CefCookieManager x0, CefStringUtf16 x1, int x2, CefCookieVisitor x3); 
}

public static interface SetCookieFunc extends Callback {

int set_cookie(CefCookieManager x0, CefStringUtf16 x1, CefCookie x2, CefSetCookieCallback x3); 
}

public static interface DeleteCookiesFunc extends Callback {

int delete_cookies(CefCookieManager x0, CefStringUtf16 x1, CefStringUtf16 x2, CefDeleteCookiesCallback x3); 
}

public static interface FlushStoreFunc extends Callback {

int flush_store(CefCookieManager x0, CefCompletionCallback x1); 
}

public CefBaseRefCounted base;

public SetSupportedSchemesFunc set_supported_schemes;

public VisitAllCookiesFunc visit_all_cookies;

public VisitUrlCookiesFunc visit_url_cookies;

public SetCookieFunc set_cookie;

public DeleteCookiesFunc delete_cookies;

public FlushStoreFunc flush_store;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "set_supported_schemes", "visit_all_cookies", "visit_url_cookies", "set_cookie", "delete_cookies", "flush_store");
 }

public void setSupportedSchemes (Pointer x1, int x2, CefCompletionCallback x3) {

  this.set_supported_schemes.set_supported_schemes(this,  x1,  x2,  x3);

}

public int visitAllCookies (CefCookieVisitor x1) {

return  this.visit_all_cookies.visit_all_cookies(this,  x1);

}

public int visitUrlCookies (String x1, int x2, CefCookieVisitor x3) {

return  this.visit_url_cookies.visit_url_cookies(this, CljCefLib.toCefString(x1),  x2,  x3);

}

public int setCookie (String x1, CefCookie x2, CefSetCookieCallback x3) {

return  this.set_cookie.set_cookie(this, CljCefLib.toCefString(x1),  x2,  x3);

}

public int deleteCookies (String x1, String x2, CefDeleteCookiesCallback x3) {

return  this.delete_cookies.delete_cookies(this, CljCefLib.toCefString(x1), CljCefLib.toCefString(x2),  x3);

}

public int flushStore (CefCompletionCallback x1) {

return  this.flush_store.flush_store(this,  x1);

}}