// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefDisplayHandler extends Structure{
public CefDisplayHandler(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnAddressChangeFunc extends Callback {

void on_address_change(CefDisplayHandler x0, CefBrowser x1, CefFrame x2, CefStringUtf16 x3); 
}

public static interface OnTitleChangeFunc extends Callback {

void on_title_change(CefDisplayHandler x0, CefBrowser x1, CefStringUtf16 x2); 
}

public static interface OnFaviconUrlchangeFunc extends Callback {

void on_favicon_urlchange(CefDisplayHandler x0, CefBrowser x1, Pointer x2); 
}

public static interface OnFullscreenModeChangeFunc extends Callback {

void on_fullscreen_mode_change(CefDisplayHandler x0, CefBrowser x1, int x2); 
}

public static interface OnTooltipFunc extends Callback {

int on_tooltip(CefDisplayHandler x0, CefBrowser x1, CefStringUtf16 x2); 
}

public static interface OnStatusMessageFunc extends Callback {

void on_status_message(CefDisplayHandler x0, CefBrowser x1, CefStringUtf16 x2); 
}

public static interface OnConsoleMessageFunc extends Callback {

int on_console_message(CefDisplayHandler x0, CefBrowser x1, int x2, CefStringUtf16 x3, CefStringUtf16 x4, int x5); 
}

public static interface OnAutoResizeFunc extends Callback {

int on_auto_resize(CefDisplayHandler x0, CefBrowser x1, CefSize x2); 
}

public static interface OnLoadingProgressChangeFunc extends Callback {

void on_loading_progress_change(CefDisplayHandler x0, CefBrowser x1, double x2); 
}

public static interface OnCursorChangeFunc extends Callback {

int on_cursor_change(CefDisplayHandler x0, CefBrowser x1, Pointer x2, int x3, CefCursorInfo x4); 
}

public CefBaseRefCounted base;

public OnAddressChangeFunc on_address_change;

public OnTitleChangeFunc on_title_change;

public OnFaviconUrlchangeFunc on_favicon_urlchange;

public OnFullscreenModeChangeFunc on_fullscreen_mode_change;

public OnTooltipFunc on_tooltip;

public OnStatusMessageFunc on_status_message;

public OnConsoleMessageFunc on_console_message;

public OnAutoResizeFunc on_auto_resize;

public OnLoadingProgressChangeFunc on_loading_progress_change;

public OnCursorChangeFunc on_cursor_change;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_address_change", "on_title_change", "on_favicon_urlchange", "on_fullscreen_mode_change", "on_tooltip", "on_status_message", "on_console_message", "on_auto_resize", "on_loading_progress_change", "on_cursor_change");
 }

public void onAddressChange (CefBrowser x1, CefFrame x2, String x3) {

  this.on_address_change.on_address_change(this,  x1,  x2, CljCefLib.toCefString(x3));

}

public void onTitleChange (CefBrowser x1, String x2) {

  this.on_title_change.on_title_change(this,  x1, CljCefLib.toCefString(x2));

}

public void onFaviconUrlchange (CefBrowser x1, Pointer x2) {

  this.on_favicon_urlchange.on_favicon_urlchange(this,  x1,  x2);

}

public void onFullscreenModeChange (CefBrowser x1, int x2) {

  this.on_fullscreen_mode_change.on_fullscreen_mode_change(this,  x1,  x2);

}

public int onTooltip (CefBrowser x1, String x2) {

return  this.on_tooltip.on_tooltip(this,  x1, CljCefLib.toCefString(x2));

}

public void onStatusMessage (CefBrowser x1, String x2) {

  this.on_status_message.on_status_message(this,  x1, CljCefLib.toCefString(x2));

}

public int onConsoleMessage (CefBrowser x1, int x2, String x3, String x4, int x5) {

return  this.on_console_message.on_console_message(this,  x1,  x2, CljCefLib.toCefString(x3), CljCefLib.toCefString(x4),  x5);

}

public int onAutoResize (CefBrowser x1, CefSize x2) {

return  this.on_auto_resize.on_auto_resize(this,  x1,  x2);

}

public void onLoadingProgressChange (CefBrowser x1, double x2) {

  this.on_loading_progress_change.on_loading_progress_change(this,  x1,  x2);

}

public int onCursorChange (CefBrowser x1, Pointer x2, int x3, CefCursorInfo x4) {

return  this.on_cursor_change.on_cursor_change(this,  x1,  x2,  x3,  x4);

}}