// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefDomnode extends Structure{
public CefDomnode(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface GetTypeFunc extends Callback {

int get_type(CefDomnode x0); 
}

public static interface IsTextFunc extends Callback {

int is_text(CefDomnode x0); 
}

public static interface IsElementFunc extends Callback {

int is_element(CefDomnode x0); 
}

public static interface IsEditableFunc extends Callback {

int is_editable(CefDomnode x0); 
}

public static interface IsFormControlElementFunc extends Callback {

int is_form_control_element(CefDomnode x0); 
}

public static interface GetFormControlElementTypeFunc extends Callback {

CefStringUtf16 get_form_control_element_type(CefDomnode x0); 
}

public static interface IsSameFunc extends Callback {

int is_same(CefDomnode x0, CefDomnode x1); 
}

public static interface GetNameFunc extends Callback {

CefStringUtf16 get_name(CefDomnode x0); 
}

public static interface GetValueFunc extends Callback {

CefStringUtf16 get_value(CefDomnode x0); 
}

public static interface SetValueFunc extends Callback {

int set_value(CefDomnode x0, CefStringUtf16 x1); 
}

public static interface GetAsMarkupFunc extends Callback {

CefStringUtf16 get_as_markup(CefDomnode x0); 
}

public static interface GetDocumentFunc extends Callback {

CefDomdocument get_document(CefDomnode x0); 
}

public static interface GetParentFunc extends Callback {

CefDomnode get_parent(CefDomnode x0); 
}

public static interface GetPreviousSiblingFunc extends Callback {

CefDomnode get_previous_sibling(CefDomnode x0); 
}

public static interface GetNextSiblingFunc extends Callback {

CefDomnode get_next_sibling(CefDomnode x0); 
}

public static interface HasChildrenFunc extends Callback {

int has_children(CefDomnode x0); 
}

public static interface GetFirstChildFunc extends Callback {

CefDomnode get_first_child(CefDomnode x0); 
}

public static interface GetLastChildFunc extends Callback {

CefDomnode get_last_child(CefDomnode x0); 
}

public static interface GetElementTagNameFunc extends Callback {

CefStringUtf16 get_element_tag_name(CefDomnode x0); 
}

public static interface HasElementAttributesFunc extends Callback {

int has_element_attributes(CefDomnode x0); 
}

public static interface HasElementAttributeFunc extends Callback {

int has_element_attribute(CefDomnode x0, CefStringUtf16 x1); 
}

public static interface GetElementAttributeFunc extends Callback {

CefStringUtf16 get_element_attribute(CefDomnode x0, CefStringUtf16 x1); 
}

public static interface GetElementAttributesFunc extends Callback {

void get_element_attributes(CefDomnode x0, Pointer x1); 
}

public static interface SetElementAttributeFunc extends Callback {

int set_element_attribute(CefDomnode x0, CefStringUtf16 x1, CefStringUtf16 x2); 
}

public static interface GetElementInnerTextFunc extends Callback {

CefStringUtf16 get_element_inner_text(CefDomnode x0); 
}

public static interface GetElementBoundsFunc extends Callback {

CefRect get_element_bounds(CefDomnode x0); 
}

public CefBaseRefCounted base;

public GetTypeFunc get_type;

public IsTextFunc is_text;

public IsElementFunc is_element;

public IsEditableFunc is_editable;

public IsFormControlElementFunc is_form_control_element;

public GetFormControlElementTypeFunc get_form_control_element_type;

public IsSameFunc is_same;

public GetNameFunc get_name;

public GetValueFunc get_value;

public SetValueFunc set_value;

public GetAsMarkupFunc get_as_markup;

public GetDocumentFunc get_document;

public GetParentFunc get_parent;

public GetPreviousSiblingFunc get_previous_sibling;

public GetNextSiblingFunc get_next_sibling;

public HasChildrenFunc has_children;

public GetFirstChildFunc get_first_child;

public GetLastChildFunc get_last_child;

public GetElementTagNameFunc get_element_tag_name;

public HasElementAttributesFunc has_element_attributes;

public HasElementAttributeFunc has_element_attribute;

public GetElementAttributeFunc get_element_attribute;

public GetElementAttributesFunc get_element_attributes;

public SetElementAttributeFunc set_element_attribute;

public GetElementInnerTextFunc get_element_inner_text;

public GetElementBoundsFunc get_element_bounds;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "get_type", "is_text", "is_element", "is_editable", "is_form_control_element", "get_form_control_element_type", "is_same", "get_name", "get_value", "set_value", "get_as_markup", "get_document", "get_parent", "get_previous_sibling", "get_next_sibling", "has_children", "get_first_child", "get_last_child", "get_element_tag_name", "has_element_attributes", "has_element_attribute", "get_element_attribute", "get_element_attributes", "set_element_attribute", "get_element_inner_text", "get_element_bounds");
 }

public int getType () {

return  this.get_type.get_type(this);

}

public int isText () {

return  this.is_text.is_text(this);

}

public int isElement () {

return  this.is_element.is_element(this);

}

public int isEditable () {

return  this.is_editable.is_editable(this);

}

public int isFormControlElement () {

return  this.is_form_control_element.is_form_control_element(this);

}

public CefStringUtf16 getFormControlElementType () {

return  this.get_form_control_element_type.get_form_control_element_type(this);

}

public int isSame (CefDomnode x1) {

return  this.is_same.is_same(this,  x1);

}

public CefStringUtf16 getName () {

return  this.get_name.get_name(this);

}

public CefStringUtf16 getValue () {

return  this.get_value.get_value(this);

}

public int setValue (String x1) {

return  this.set_value.set_value(this, CljCefLib.toCefString(x1));

}

public CefStringUtf16 getAsMarkup () {

return  this.get_as_markup.get_as_markup(this);

}

public CefDomdocument getDocument () {

return  this.get_document.get_document(this);

}

public CefDomnode getParent () {

return  this.get_parent.get_parent(this);

}

public CefDomnode getPreviousSibling () {

return  this.get_previous_sibling.get_previous_sibling(this);

}

public CefDomnode getNextSibling () {

return  this.get_next_sibling.get_next_sibling(this);

}

public int hasChildren () {

return  this.has_children.has_children(this);

}

public CefDomnode getFirstChild () {

return  this.get_first_child.get_first_child(this);

}

public CefDomnode getLastChild () {

return  this.get_last_child.get_last_child(this);

}

public CefStringUtf16 getElementTagName () {

return  this.get_element_tag_name.get_element_tag_name(this);

}

public int hasElementAttributes () {

return  this.has_element_attributes.has_element_attributes(this);

}

public int hasElementAttribute (String x1) {

return  this.has_element_attribute.has_element_attribute(this, CljCefLib.toCefString(x1));

}

public CefStringUtf16 getElementAttribute (String x1) {

return  this.get_element_attribute.get_element_attribute(this, CljCefLib.toCefString(x1));

}

public void getElementAttributes (Pointer x1) {

  this.get_element_attributes.get_element_attributes(this,  x1);

}

public int setElementAttribute (String x1, String x2) {

return  this.set_element_attribute.set_element_attribute(this, CljCefLib.toCefString(x1), CljCefLib.toCefString(x2));

}

public CefStringUtf16 getElementInnerText () {

return  this.get_element_inner_text.get_element_inner_text(this);

}

public CefRect getElementBounds () {

return  this.get_element_bounds.get_element_bounds(this);

}}