// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefDialogHandler extends Structure{
public CefDialogHandler(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnFileDialogFunc extends Callback {

int on_file_dialog(CefDialogHandler x0, CefBrowser x1, int x2, CefStringUtf16 x3, CefStringUtf16 x4, Pointer x5, int x6, CefFileDialogCallback x7); 
}

public CefBaseRefCounted base;

public OnFileDialogFunc on_file_dialog;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_file_dialog");
 }

public int onFileDialog (CefBrowser x1, int x2, String x3, String x4, Pointer x5, int x6, CefFileDialogCallback x7) {

return  this.on_file_dialog.on_file_dialog(this,  x1,  x2, CljCefLib.toCefString(x3), CljCefLib.toCefString(x4),  x5,  x6,  x7);

}}