// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefJsdialogHandler extends Structure{
public CefJsdialogHandler(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnJsdialogFunc extends Callback {

int on_jsdialog(CefJsdialogHandler x0, CefBrowser x1, CefStringUtf16 x2, int x3, CefStringUtf16 x4, CefStringUtf16 x5, CefJsdialogCallback x6, Pointer x7); 
}

public static interface OnBeforeUnloadDialogFunc extends Callback {

int on_before_unload_dialog(CefJsdialogHandler x0, CefBrowser x1, CefStringUtf16 x2, int x3, CefJsdialogCallback x4); 
}

public static interface OnResetDialogStateFunc extends Callback {

void on_reset_dialog_state(CefJsdialogHandler x0, CefBrowser x1); 
}

public static interface OnDialogClosedFunc extends Callback {

void on_dialog_closed(CefJsdialogHandler x0, CefBrowser x1); 
}

public CefBaseRefCounted base;

public OnJsdialogFunc on_jsdialog;

public OnBeforeUnloadDialogFunc on_before_unload_dialog;

public OnResetDialogStateFunc on_reset_dialog_state;

public OnDialogClosedFunc on_dialog_closed;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_jsdialog", "on_before_unload_dialog", "on_reset_dialog_state", "on_dialog_closed");
 }

public int onJsdialog (CefBrowser x1, String x2, int x3, String x4, String x5, CefJsdialogCallback x6, Pointer x7) {

return  this.on_jsdialog.on_jsdialog(this,  x1, CljCefLib.toCefString(x2),  x3, CljCefLib.toCefString(x4), CljCefLib.toCefString(x5),  x6,  x7);

}

public int onBeforeUnloadDialog (CefBrowser x1, String x2, int x3, CefJsdialogCallback x4) {

return  this.on_before_unload_dialog.on_before_unload_dialog(this,  x1, CljCefLib.toCefString(x2),  x3,  x4);

}

public void onResetDialogState (CefBrowser x1) {

  this.on_reset_dialog_state.on_reset_dialog_state(this,  x1);

}

public void onDialogClosed (CefBrowser x1) {

  this.on_dialog_closed.on_dialog_closed(this,  x1);

}}