// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefLifeSpanHandler extends Structure{
public CefLifeSpanHandler(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnBeforePopupFunc extends Callback {

int on_before_popup(CefLifeSpanHandler x0, CefBrowser x1, CefFrame x2, CefStringUtf16 x3, CefStringUtf16 x4, int x5, int x6, CefPopupFeatures x7, CefWindowInfo x8, Pointer x9, CefBrowserSettings x10, Pointer x11, Pointer x12); 
}

public static interface OnAfterCreatedFunc extends Callback {

void on_after_created(CefLifeSpanHandler x0, CefBrowser x1); 
}

public static interface DoCloseFunc extends Callback {

int do_close(CefLifeSpanHandler x0, CefBrowser x1); 
}

public static interface OnBeforeCloseFunc extends Callback {

void on_before_close(CefLifeSpanHandler x0, CefBrowser x1); 
}

public CefBaseRefCounted base;

public OnBeforePopupFunc on_before_popup;

public OnAfterCreatedFunc on_after_created;

public DoCloseFunc do_close;

public OnBeforeCloseFunc on_before_close;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_before_popup", "on_after_created", "do_close", "on_before_close");
 }

public int onBeforePopup (CefBrowser x1, CefFrame x2, String x3, String x4, int x5, int x6, CefPopupFeatures x7, CefWindowInfo x8, Pointer x9, CefBrowserSettings x10, Pointer x11, Pointer x12) {

return  this.on_before_popup.on_before_popup(this,  x1,  x2, CljCefLib.toCefString(x3), CljCefLib.toCefString(x4),  x5,  x6,  x7,  x8,  x9,  x10,  x11,  x12);

}

public void onAfterCreated (CefBrowser x1) {

  this.on_after_created.on_after_created(this,  x1);

}

public int doClose (CefBrowser x1) {

return  this.do_close.do_close(this,  x1);

}

public void onBeforeClose (CefBrowser x1) {

  this.on_before_close.on_before_close(this,  x1);

}}