// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefMediaObserver extends Structure{
public CefMediaObserver(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnSinksFunc extends Callback {

void on_sinks(CefMediaObserver x0, SizeT x1, Pointer x2); 
}

public static interface OnRoutesFunc extends Callback {

void on_routes(CefMediaObserver x0, SizeT x1, Pointer x2); 
}

public static interface OnRouteStateChangedFunc extends Callback {

void on_route_state_changed(CefMediaObserver x0, CefMediaRoute x1, int x2); 
}

public static interface OnRouteMessageReceivedFunc extends Callback {

void on_route_message_received(CefMediaObserver x0, CefMediaRoute x1, Pointer x2, SizeT x3); 
}

public CefBaseRefCounted base;

public OnSinksFunc on_sinks;

public OnRoutesFunc on_routes;

public OnRouteStateChangedFunc on_route_state_changed;

public OnRouteMessageReceivedFunc on_route_message_received;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_sinks", "on_routes", "on_route_state_changed", "on_route_message_received");
 }

public void onSinks (SizeT x1, Pointer x2) {

  this.on_sinks.on_sinks(this,  x1,  x2);

}

public void onRoutes (SizeT x1, Pointer x2) {

  this.on_routes.on_routes(this,  x1,  x2);

}

public void onRouteStateChanged (CefMediaRoute x1, int x2) {

  this.on_route_state_changed.on_route_state_changed(this,  x1,  x2);

}

public void onRouteMessageReceived (CefMediaRoute x1, Pointer x2, SizeT x3) {

  this.on_route_message_received.on_route_message_received(this,  x1,  x2,  x3);

}}