// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefMediaSink extends Structure{
public CefMediaSink(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface GetIdFunc extends Callback {

CefStringUtf16 get_id(CefMediaSink x0); 
}

public static interface GetNameFunc extends Callback {

CefStringUtf16 get_name(CefMediaSink x0); 
}

public static interface GetDescriptionFunc extends Callback {

CefStringUtf16 get_description(CefMediaSink x0); 
}

public static interface GetIconTypeFunc extends Callback {

int get_icon_type(CefMediaSink x0); 
}

public static interface GetDeviceInfoFunc extends Callback {

void get_device_info(CefMediaSink x0, CefMediaSinkDeviceInfoCallback x1); 
}

public static interface IsCastSinkFunc extends Callback {

int is_cast_sink(CefMediaSink x0); 
}

public static interface IsDialSinkFunc extends Callback {

int is_dial_sink(CefMediaSink x0); 
}

public static interface IsCompatibleWithFunc extends Callback {

int is_compatible_with(CefMediaSink x0, CefMediaSource x1); 
}

public CefBaseRefCounted base;

public GetIdFunc get_id;

public GetNameFunc get_name;

public GetDescriptionFunc get_description;

public GetIconTypeFunc get_icon_type;

public GetDeviceInfoFunc get_device_info;

public IsCastSinkFunc is_cast_sink;

public IsDialSinkFunc is_dial_sink;

public IsCompatibleWithFunc is_compatible_with;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "get_id", "get_name", "get_description", "get_icon_type", "get_device_info", "is_cast_sink", "is_dial_sink", "is_compatible_with");
 }

public CefStringUtf16 getId () {

return  this.get_id.get_id(this);

}

public CefStringUtf16 getName () {

return  this.get_name.get_name(this);

}

public CefStringUtf16 getDescription () {

return  this.get_description.get_description(this);

}

public int getIconType () {

return  this.get_icon_type.get_icon_type(this);

}

public void getDeviceInfo (CefMediaSinkDeviceInfoCallback x1) {

  this.get_device_info.get_device_info(this,  x1);

}

public int isCastSink () {

return  this.is_cast_sink.is_cast_sink(this);

}

public int isDialSink () {

return  this.is_dial_sink.is_dial_sink(this);

}

public int isCompatibleWith (CefMediaSource x1) {

return  this.is_compatible_with.is_compatible_with(this,  x1);

}}