// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefMenuModel extends Structure{
public CefMenuModel(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface IsSubMenuFunc extends Callback {

int is_sub_menu(CefMenuModel x0); 
}

public static interface ClearFunc extends Callback {

int clear(CefMenuModel x0); 
}

public static interface GetCountFunc extends Callback {

int get_count(CefMenuModel x0); 
}

public static interface AddSeparatorFunc extends Callback {

int add_separator(CefMenuModel x0); 
}

public static interface AddItemFunc extends Callback {

int add_item(CefMenuModel x0, int x1, CefStringUtf16 x2); 
}

public static interface AddCheckItemFunc extends Callback {

int add_check_item(CefMenuModel x0, int x1, CefStringUtf16 x2); 
}

public static interface AddRadioItemFunc extends Callback {

int add_radio_item(CefMenuModel x0, int x1, CefStringUtf16 x2, int x3); 
}

public static interface AddSubMenuFunc extends Callback {

CefMenuModel add_sub_menu(CefMenuModel x0, int x1, CefStringUtf16 x2); 
}

public static interface InsertSeparatorAtFunc extends Callback {

int insert_separator_at(CefMenuModel x0, int x1); 
}

public static interface InsertItemAtFunc extends Callback {

int insert_item_at(CefMenuModel x0, int x1, int x2, CefStringUtf16 x3); 
}

public static interface InsertCheckItemAtFunc extends Callback {

int insert_check_item_at(CefMenuModel x0, int x1, int x2, CefStringUtf16 x3); 
}

public static interface InsertRadioItemAtFunc extends Callback {

int insert_radio_item_at(CefMenuModel x0, int x1, int x2, CefStringUtf16 x3, int x4); 
}

public static interface InsertSubMenuAtFunc extends Callback {

CefMenuModel insert_sub_menu_at(CefMenuModel x0, int x1, int x2, CefStringUtf16 x3); 
}

public static interface RemoveFunc extends Callback {

int remove(CefMenuModel x0, int x1); 
}

public static interface RemoveAtFunc extends Callback {

int remove_at(CefMenuModel x0, int x1); 
}

public static interface GetIndexOfFunc extends Callback {

int get_index_of(CefMenuModel x0, int x1); 
}

public static interface GetCommandIdAtFunc extends Callback {

int get_command_id_at(CefMenuModel x0, int x1); 
}

public static interface SetCommandIdAtFunc extends Callback {

int set_command_id_at(CefMenuModel x0, int x1, int x2); 
}

public static interface GetLabelFunc extends Callback {

CefStringUtf16 get_label(CefMenuModel x0, int x1); 
}

public static interface GetLabelAtFunc extends Callback {

CefStringUtf16 get_label_at(CefMenuModel x0, int x1); 
}

public static interface SetLabelFunc extends Callback {

int set_label(CefMenuModel x0, int x1, CefStringUtf16 x2); 
}

public static interface SetLabelAtFunc extends Callback {

int set_label_at(CefMenuModel x0, int x1, CefStringUtf16 x2); 
}

public static interface GetTypeFunc extends Callback {

int get_type(CefMenuModel x0, int x1); 
}

public static interface GetTypeAtFunc extends Callback {

int get_type_at(CefMenuModel x0, int x1); 
}

public static interface GetGroupIdFunc extends Callback {

int get_group_id(CefMenuModel x0, int x1); 
}

public static interface GetGroupIdAtFunc extends Callback {

int get_group_id_at(CefMenuModel x0, int x1); 
}

public static interface SetGroupIdFunc extends Callback {

int set_group_id(CefMenuModel x0, int x1, int x2); 
}

public static interface SetGroupIdAtFunc extends Callback {

int set_group_id_at(CefMenuModel x0, int x1, int x2); 
}

public static interface GetSubMenuFunc extends Callback {

CefMenuModel get_sub_menu(CefMenuModel x0, int x1); 
}

public static interface GetSubMenuAtFunc extends Callback {

CefMenuModel get_sub_menu_at(CefMenuModel x0, int x1); 
}

public static interface IsVisibleFunc extends Callback {

int is_visible(CefMenuModel x0, int x1); 
}

public static interface IsVisibleAtFunc extends Callback {

int is_visible_at(CefMenuModel x0, int x1); 
}

public static interface SetVisibleFunc extends Callback {

int set_visible(CefMenuModel x0, int x1, int x2); 
}

public static interface SetVisibleAtFunc extends Callback {

int set_visible_at(CefMenuModel x0, int x1, int x2); 
}

public static interface IsEnabledFunc extends Callback {

int is_enabled(CefMenuModel x0, int x1); 
}

public static interface IsEnabledAtFunc extends Callback {

int is_enabled_at(CefMenuModel x0, int x1); 
}

public static interface SetEnabledFunc extends Callback {

int set_enabled(CefMenuModel x0, int x1, int x2); 
}

public static interface SetEnabledAtFunc extends Callback {

int set_enabled_at(CefMenuModel x0, int x1, int x2); 
}

public static interface IsCheckedFunc extends Callback {

int is_checked(CefMenuModel x0, int x1); 
}

public static interface IsCheckedAtFunc extends Callback {

int is_checked_at(CefMenuModel x0, int x1); 
}

public static interface SetCheckedFunc extends Callback {

int set_checked(CefMenuModel x0, int x1, int x2); 
}

public static interface SetCheckedAtFunc extends Callback {

int set_checked_at(CefMenuModel x0, int x1, int x2); 
}

public static interface HasAcceleratorFunc extends Callback {

int has_accelerator(CefMenuModel x0, int x1); 
}

public static interface HasAcceleratorAtFunc extends Callback {

int has_accelerator_at(CefMenuModel x0, int x1); 
}

public static interface SetAcceleratorFunc extends Callback {

int set_accelerator(CefMenuModel x0, int x1, int x2, int x3, int x4, int x5); 
}

public static interface SetAcceleratorAtFunc extends Callback {

int set_accelerator_at(CefMenuModel x0, int x1, int x2, int x3, int x4, int x5); 
}

public static interface RemoveAcceleratorFunc extends Callback {

int remove_accelerator(CefMenuModel x0, int x1); 
}

public static interface RemoveAcceleratorAtFunc extends Callback {

int remove_accelerator_at(CefMenuModel x0, int x1); 
}

public static interface GetAcceleratorFunc extends Callback {

int get_accelerator(CefMenuModel x0, int x1, Pointer x2, Pointer x3, Pointer x4, Pointer x5); 
}

public static interface GetAcceleratorAtFunc extends Callback {

int get_accelerator_at(CefMenuModel x0, int x1, Pointer x2, Pointer x3, Pointer x4, Pointer x5); 
}

public static interface SetColorFunc extends Callback {

int set_color(CefMenuModel x0, int x1, int x2, int x3); 
}

public static interface SetColorAtFunc extends Callback {

int set_color_at(CefMenuModel x0, int x1, int x2, int x3); 
}

public static interface GetColorFunc extends Callback {

int get_color(CefMenuModel x0, int x1, int x2, int x3); 
}

public static interface GetColorAtFunc extends Callback {

int get_color_at(CefMenuModel x0, int x1, int x2, int x3); 
}

public static interface SetFontListFunc extends Callback {

int set_font_list(CefMenuModel x0, int x1, CefStringUtf16 x2); 
}

public static interface SetFontListAtFunc extends Callback {

int set_font_list_at(CefMenuModel x0, int x1, CefStringUtf16 x2); 
}

public CefBaseRefCounted base;

public IsSubMenuFunc is_sub_menu;

public ClearFunc clear;

public GetCountFunc get_count;

public AddSeparatorFunc add_separator;

public AddItemFunc add_item;

public AddCheckItemFunc add_check_item;

public AddRadioItemFunc add_radio_item;

public AddSubMenuFunc add_sub_menu;

public InsertSeparatorAtFunc insert_separator_at;

public InsertItemAtFunc insert_item_at;

public InsertCheckItemAtFunc insert_check_item_at;

public InsertRadioItemAtFunc insert_radio_item_at;

public InsertSubMenuAtFunc insert_sub_menu_at;

public RemoveFunc remove;

public RemoveAtFunc remove_at;

public GetIndexOfFunc get_index_of;

public GetCommandIdAtFunc get_command_id_at;

public SetCommandIdAtFunc set_command_id_at;

public GetLabelFunc get_label;

public GetLabelAtFunc get_label_at;

public SetLabelFunc set_label;

public SetLabelAtFunc set_label_at;

public GetTypeFunc get_type;

public GetTypeAtFunc get_type_at;

public GetGroupIdFunc get_group_id;

public GetGroupIdAtFunc get_group_id_at;

public SetGroupIdFunc set_group_id;

public SetGroupIdAtFunc set_group_id_at;

public GetSubMenuFunc get_sub_menu;

public GetSubMenuAtFunc get_sub_menu_at;

public IsVisibleFunc is_visible;

public IsVisibleAtFunc is_visible_at;

public SetVisibleFunc set_visible;

public SetVisibleAtFunc set_visible_at;

public IsEnabledFunc is_enabled;

public IsEnabledAtFunc is_enabled_at;

public SetEnabledFunc set_enabled;

public SetEnabledAtFunc set_enabled_at;

public IsCheckedFunc is_checked;

public IsCheckedAtFunc is_checked_at;

public SetCheckedFunc set_checked;

public SetCheckedAtFunc set_checked_at;

public HasAcceleratorFunc has_accelerator;

public HasAcceleratorAtFunc has_accelerator_at;

public SetAcceleratorFunc set_accelerator;

public SetAcceleratorAtFunc set_accelerator_at;

public RemoveAcceleratorFunc remove_accelerator;

public RemoveAcceleratorAtFunc remove_accelerator_at;

public GetAcceleratorFunc get_accelerator;

public GetAcceleratorAtFunc get_accelerator_at;

public SetColorFunc set_color;

public SetColorAtFunc set_color_at;

public GetColorFunc get_color;

public GetColorAtFunc get_color_at;

public SetFontListFunc set_font_list;

public SetFontListAtFunc set_font_list_at;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "is_sub_menu", "clear", "get_count", "add_separator", "add_item", "add_check_item", "add_radio_item", "add_sub_menu", "insert_separator_at", "insert_item_at", "insert_check_item_at", "insert_radio_item_at", "insert_sub_menu_at", "remove", "remove_at", "get_index_of", "get_command_id_at", "set_command_id_at", "get_label", "get_label_at", "set_label", "set_label_at", "get_type", "get_type_at", "get_group_id", "get_group_id_at", "set_group_id", "set_group_id_at", "get_sub_menu", "get_sub_menu_at", "is_visible", "is_visible_at", "set_visible", "set_visible_at", "is_enabled", "is_enabled_at", "set_enabled", "set_enabled_at", "is_checked", "is_checked_at", "set_checked", "set_checked_at", "has_accelerator", "has_accelerator_at", "set_accelerator", "set_accelerator_at", "remove_accelerator", "remove_accelerator_at", "get_accelerator", "get_accelerator_at", "set_color", "set_color_at", "get_color", "get_color_at", "set_font_list", "set_font_list_at");
 }

public int isSubMenu () {

return  this.is_sub_menu.is_sub_menu(this);

}



public int getCount () {

return  this.get_count.get_count(this);

}

public int addSeparator () {

return  this.add_separator.add_separator(this);

}

public int addItem (int x1, String x2) {

return  this.add_item.add_item(this,  x1, CljCefLib.toCefString(x2));

}

public int addCheckItem (int x1, String x2) {

return  this.add_check_item.add_check_item(this,  x1, CljCefLib.toCefString(x2));

}

public int addRadioItem (int x1, String x2, int x3) {

return  this.add_radio_item.add_radio_item(this,  x1, CljCefLib.toCefString(x2),  x3);

}

public CefMenuModel addSubMenu (int x1, String x2) {

return  this.add_sub_menu.add_sub_menu(this,  x1, CljCefLib.toCefString(x2));

}

public int insertSeparatorAt (int x1) {

return  this.insert_separator_at.insert_separator_at(this,  x1);

}

public int insertItemAt (int x1, int x2, String x3) {

return  this.insert_item_at.insert_item_at(this,  x1,  x2, CljCefLib.toCefString(x3));

}

public int insertCheckItemAt (int x1, int x2, String x3) {

return  this.insert_check_item_at.insert_check_item_at(this,  x1,  x2, CljCefLib.toCefString(x3));

}

public int insertRadioItemAt (int x1, int x2, String x3, int x4) {

return  this.insert_radio_item_at.insert_radio_item_at(this,  x1,  x2, CljCefLib.toCefString(x3),  x4);

}

public CefMenuModel insertSubMenuAt (int x1, int x2, String x3) {

return  this.insert_sub_menu_at.insert_sub_menu_at(this,  x1,  x2, CljCefLib.toCefString(x3));

}

public int remove (int x1) {

return  this.remove.remove(this,  x1);

}

public int removeAt (int x1) {

return  this.remove_at.remove_at(this,  x1);

}

public int getIndexOf (int x1) {

return  this.get_index_of.get_index_of(this,  x1);

}

public int getCommandIdAt (int x1) {

return  this.get_command_id_at.get_command_id_at(this,  x1);

}

public int setCommandIdAt (int x1, int x2) {

return  this.set_command_id_at.set_command_id_at(this,  x1,  x2);

}

public CefStringUtf16 getLabel (int x1) {

return  this.get_label.get_label(this,  x1);

}

public CefStringUtf16 getLabelAt (int x1) {

return  this.get_label_at.get_label_at(this,  x1);

}

public int setLabel (int x1, String x2) {

return  this.set_label.set_label(this,  x1, CljCefLib.toCefString(x2));

}

public int setLabelAt (int x1, String x2) {

return  this.set_label_at.set_label_at(this,  x1, CljCefLib.toCefString(x2));

}

public int getType (int x1) {

return  this.get_type.get_type(this,  x1);

}

public int getTypeAt (int x1) {

return  this.get_type_at.get_type_at(this,  x1);

}

public int getGroupId (int x1) {

return  this.get_group_id.get_group_id(this,  x1);

}

public int getGroupIdAt (int x1) {

return  this.get_group_id_at.get_group_id_at(this,  x1);

}

public int setGroupId (int x1, int x2) {

return  this.set_group_id.set_group_id(this,  x1,  x2);

}

public int setGroupIdAt (int x1, int x2) {

return  this.set_group_id_at.set_group_id_at(this,  x1,  x2);

}

public CefMenuModel getSubMenu (int x1) {

return  this.get_sub_menu.get_sub_menu(this,  x1);

}

public CefMenuModel getSubMenuAt (int x1) {

return  this.get_sub_menu_at.get_sub_menu_at(this,  x1);

}

public int isVisible (int x1) {

return  this.is_visible.is_visible(this,  x1);

}

public int isVisibleAt (int x1) {

return  this.is_visible_at.is_visible_at(this,  x1);

}

public int setVisible (int x1, int x2) {

return  this.set_visible.set_visible(this,  x1,  x2);

}

public int setVisibleAt (int x1, int x2) {

return  this.set_visible_at.set_visible_at(this,  x1,  x2);

}

public int isEnabled (int x1) {

return  this.is_enabled.is_enabled(this,  x1);

}

public int isEnabledAt (int x1) {

return  this.is_enabled_at.is_enabled_at(this,  x1);

}

public int setEnabled (int x1, int x2) {

return  this.set_enabled.set_enabled(this,  x1,  x2);

}

public int setEnabledAt (int x1, int x2) {

return  this.set_enabled_at.set_enabled_at(this,  x1,  x2);

}

public int isChecked (int x1) {

return  this.is_checked.is_checked(this,  x1);

}

public int isCheckedAt (int x1) {

return  this.is_checked_at.is_checked_at(this,  x1);

}

public int setChecked (int x1, int x2) {

return  this.set_checked.set_checked(this,  x1,  x2);

}

public int setCheckedAt (int x1, int x2) {

return  this.set_checked_at.set_checked_at(this,  x1,  x2);

}

public int hasAccelerator (int x1) {

return  this.has_accelerator.has_accelerator(this,  x1);

}

public int hasAcceleratorAt (int x1) {

return  this.has_accelerator_at.has_accelerator_at(this,  x1);

}

public int setAccelerator (int x1, int x2, int x3, int x4, int x5) {

return  this.set_accelerator.set_accelerator(this,  x1,  x2,  x3,  x4,  x5);

}

public int setAcceleratorAt (int x1, int x2, int x3, int x4, int x5) {

return  this.set_accelerator_at.set_accelerator_at(this,  x1,  x2,  x3,  x4,  x5);

}

public int removeAccelerator (int x1) {

return  this.remove_accelerator.remove_accelerator(this,  x1);

}

public int removeAcceleratorAt (int x1) {

return  this.remove_accelerator_at.remove_accelerator_at(this,  x1);

}

public int getAccelerator (int x1, Pointer x2, Pointer x3, Pointer x4, Pointer x5) {

return  this.get_accelerator.get_accelerator(this,  x1,  x2,  x3,  x4,  x5);

}

public int getAcceleratorAt (int x1, Pointer x2, Pointer x3, Pointer x4, Pointer x5) {

return  this.get_accelerator_at.get_accelerator_at(this,  x1,  x2,  x3,  x4,  x5);

}

public int setColor (int x1, int x2, int x3) {

return  this.set_color.set_color(this,  x1,  x2,  x3);

}

public int setColorAt (int x1, int x2, int x3) {

return  this.set_color_at.set_color_at(this,  x1,  x2,  x3);

}

public int getColor (int x1, int x2, int x3) {

return  this.get_color.get_color(this,  x1,  x2,  x3);

}

public int getColorAt (int x1, int x2, int x3) {

return  this.get_color_at.get_color_at(this,  x1,  x2,  x3);

}

public int setFontList (int x1, String x2) {

return  this.set_font_list.set_font_list(this,  x1, CljCefLib.toCefString(x2));

}

public int setFontListAt (int x1, String x2) {

return  this.set_font_list_at.set_font_list_at(this,  x1, CljCefLib.toCefString(x2));

}}