// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefMenuModelDelegate extends Structure{
public CefMenuModelDelegate(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface ExecuteCommandFunc extends Callback {

void execute_command(CefMenuModelDelegate x0, CefMenuModel x1, int x2, int x3); 
}

public static interface MouseOutsideMenuFunc extends Callback {

void mouse_outside_menu(CefMenuModelDelegate x0, CefMenuModel x1, CefPoint x2); 
}

public static interface UnhandledOpenSubmenuFunc extends Callback {

void unhandled_open_submenu(CefMenuModelDelegate x0, CefMenuModel x1, int x2); 
}

public static interface UnhandledCloseSubmenuFunc extends Callback {

void unhandled_close_submenu(CefMenuModelDelegate x0, CefMenuModel x1, int x2); 
}

public static interface MenuWillShowFunc extends Callback {

void menu_will_show(CefMenuModelDelegate x0, CefMenuModel x1); 
}

public static interface MenuClosedFunc extends Callback {

void menu_closed(CefMenuModelDelegate x0, CefMenuModel x1); 
}

public static interface FormatLabelFunc extends Callback {

int format_label(CefMenuModelDelegate x0, CefMenuModel x1, CefStringUtf16 x2); 
}

public CefBaseRefCounted base;

public ExecuteCommandFunc execute_command;

public MouseOutsideMenuFunc mouse_outside_menu;

public UnhandledOpenSubmenuFunc unhandled_open_submenu;

public UnhandledCloseSubmenuFunc unhandled_close_submenu;

public MenuWillShowFunc menu_will_show;

public MenuClosedFunc menu_closed;

public FormatLabelFunc format_label;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "execute_command", "mouse_outside_menu", "unhandled_open_submenu", "unhandled_close_submenu", "menu_will_show", "menu_closed", "format_label");
 }

public void executeCommand (CefMenuModel x1, int x2, int x3) {

  this.execute_command.execute_command(this,  x1,  x2,  x3);

}

public void mouseOutsideMenu (CefMenuModel x1, CefPoint x2) {

  this.mouse_outside_menu.mouse_outside_menu(this,  x1,  x2);

}

public void unhandledOpenSubmenu (CefMenuModel x1, int x2) {

  this.unhandled_open_submenu.unhandled_open_submenu(this,  x1,  x2);

}

public void unhandledCloseSubmenu (CefMenuModel x1, int x2) {

  this.unhandled_close_submenu.unhandled_close_submenu(this,  x1,  x2);

}

public void menuWillShow (CefMenuModel x1) {

  this.menu_will_show.menu_will_show(this,  x1);

}

public void menuClosed (CefMenuModel x1) {

  this.menu_closed.menu_closed(this,  x1);

}

public int formatLabel (CefMenuModel x1, String x2) {

return  this.format_label.format_label(this,  x1, CljCefLib.toCefString(x2));

}}