// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefPdfPrintCallback extends Structure{
public CefPdfPrintCallback(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnPdfPrintFinishedFunc extends Callback {

void on_pdf_print_finished(CefPdfPrintCallback x0, CefStringUtf16 x1, int x2); 
}

public CefBaseRefCounted base;

public OnPdfPrintFinishedFunc on_pdf_print_finished;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_pdf_print_finished");
 }

public void onPdfPrintFinished (String x1, int x2) {

  this.on_pdf_print_finished.on_pdf_print_finished(this, CljCefLib.toCefString(x1),  x2);

}}