// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefRegisterCdmCallback extends Structure{
public CefRegisterCdmCallback(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnCdmRegistrationCompleteFunc extends Callback {

void on_cdm_registration_complete(CefRegisterCdmCallback x0, int x1, CefStringUtf16 x2); 
}

public CefBaseRefCounted base;

public OnCdmRegistrationCompleteFunc on_cdm_registration_complete;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_cdm_registration_complete");
 }

public void onCdmRegistrationComplete (int x1, String x2) {

  this.on_cdm_registration_complete.on_cdm_registration_complete(this,  x1, CljCefLib.toCefString(x2));

}}