// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefRequestContextHandler extends Structure{
public CefRequestContextHandler(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnRequestContextInitializedFunc extends Callback {

void on_request_context_initialized(CefRequestContextHandler x0, CefRequestContext x1); 
}

public static interface OnBeforePluginLoadFunc extends Callback {

int on_before_plugin_load(CefRequestContextHandler x0, CefStringUtf16 x1, CefStringUtf16 x2, int x3, CefStringUtf16 x4, CefWebPluginInfo x5, int x6); 
}

public static interface GetResourceRequestHandlerFunc extends Callback {

CefResourceRequestHandler get_resource_request_handler(CefRequestContextHandler x0, CefBrowser x1, CefFrame x2, CefRequest x3, int x4, int x5, CefStringUtf16 x6, Pointer x7); 
}

public CefBaseRefCounted base;

public OnRequestContextInitializedFunc on_request_context_initialized;

public OnBeforePluginLoadFunc on_before_plugin_load;

public GetResourceRequestHandlerFunc get_resource_request_handler;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_request_context_initialized", "on_before_plugin_load", "get_resource_request_handler");
 }

public void onRequestContextInitialized (CefRequestContext x1) {

  this.on_request_context_initialized.on_request_context_initialized(this,  x1);

}

public int onBeforePluginLoad (String x1, String x2, int x3, String x4, CefWebPluginInfo x5, int x6) {

return  this.on_before_plugin_load.on_before_plugin_load(this, CljCefLib.toCefString(x1), CljCefLib.toCefString(x2),  x3, CljCefLib.toCefString(x4),  x5,  x6);

}

public CefResourceRequestHandler getResourceRequestHandler (CefBrowser x1, CefFrame x2, CefRequest x3, int x4, int x5, String x6, Pointer x7) {

return  this.get_resource_request_handler.get_resource_request_handler(this,  x1,  x2,  x3,  x4,  x5, CljCefLib.toCefString(x6),  x7);

}}