// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefSelectClientCertificateCallback extends Structure{
public CefSelectClientCertificateCallback(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface SelectFunc extends Callback {

void select(CefSelectClientCertificateCallback x0, CefX509certificate x1); 
}

public CefBaseRefCounted base;

public SelectFunc select;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "select");
 }

public void select (CefX509certificate x1) {

  this.select.select(this,  x1);

}}