// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefUrlrequestClient extends Structure{
public CefUrlrequestClient(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface OnRequestCompleteFunc extends Callback {

void on_request_complete(CefUrlrequestClient x0, CefUrlrequest x1); 
}

public static interface OnUploadProgressFunc extends Callback {

void on_upload_progress(CefUrlrequestClient x0, CefUrlrequest x1, long x2, long x3); 
}

public static interface OnDownloadProgressFunc extends Callback {

void on_download_progress(CefUrlrequestClient x0, CefUrlrequest x1, long x2, long x3); 
}

public static interface OnDownloadDataFunc extends Callback {

void on_download_data(CefUrlrequestClient x0, CefUrlrequest x1, Pointer x2, SizeT x3); 
}

public static interface GetAuthCredentialsFunc extends Callback {

int get_auth_credentials(CefUrlrequestClient x0, int x1, CefStringUtf16 x2, int x3, CefStringUtf16 x4, CefStringUtf16 x5, CefAuthCallback x6); 
}

public CefBaseRefCounted base;

public OnRequestCompleteFunc on_request_complete;

public OnUploadProgressFunc on_upload_progress;

public OnDownloadProgressFunc on_download_progress;

public OnDownloadDataFunc on_download_data;

public GetAuthCredentialsFunc get_auth_credentials;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "on_request_complete", "on_upload_progress", "on_download_progress", "on_download_data", "get_auth_credentials");
 }

public void onRequestComplete (CefUrlrequest x1) {

  this.on_request_complete.on_request_complete(this,  x1);

}

public void onUploadProgress (CefUrlrequest x1, long x2, long x3) {

  this.on_upload_progress.on_upload_progress(this,  x1,  x2,  x3);

}

public void onDownloadProgress (CefUrlrequest x1, long x2, long x3) {

  this.on_download_progress.on_download_progress(this,  x1,  x2,  x3);

}

public void onDownloadData (CefUrlrequest x1, Pointer x2, SizeT x3) {

  this.on_download_data.on_download_data(this,  x1,  x2,  x3);

}

public int getAuthCredentials (int x1, String x2, int x3, String x4, String x5, CefAuthCallback x6) {

return  this.get_auth_credentials.get_auth_credentials(this,  x1, CljCefLib.toCefString(x2),  x3, CljCefLib.toCefString(x4), CljCefLib.toCefString(x5),  x6);

}}