// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefV8context extends Structure{
public CefV8context(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface GetTaskRunnerFunc extends Callback {

CefTaskRunner get_task_runner(CefV8context x0); 
}

public static interface IsValidFunc extends Callback {

int is_valid(CefV8context x0); 
}

public static interface GetBrowserFunc extends Callback {

CefBrowser get_browser(CefV8context x0); 
}

public static interface GetFrameFunc extends Callback {

CefFrame get_frame(CefV8context x0); 
}

public static interface GetGlobalFunc extends Callback {

CefV8value get_global(CefV8context x0); 
}

public static interface EnterFunc extends Callback {

int enter(CefV8context x0); 
}

public static interface ExitFunc extends Callback {

int exit(CefV8context x0); 
}

public static interface IsSameFunc extends Callback {

int is_same(CefV8context x0, CefV8context x1); 
}

public static interface EvalFunc extends Callback {

int eval(CefV8context x0, CefStringUtf16 x1, CefStringUtf16 x2, int x3, Pointer x4, Pointer x5); 
}

public CefBaseRefCounted base;

public GetTaskRunnerFunc get_task_runner;

public IsValidFunc is_valid;

public GetBrowserFunc get_browser;

public GetFrameFunc get_frame;

public GetGlobalFunc get_global;

public EnterFunc enter;

public ExitFunc exit;

public IsSameFunc is_same;

public EvalFunc eval;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "get_task_runner", "is_valid", "get_browser", "get_frame", "get_global", "enter", "exit", "is_same", "eval");
 }

public CefTaskRunner getTaskRunner () {

return  this.get_task_runner.get_task_runner(this);

}

public int isValid () {

return  this.is_valid.is_valid(this);

}

public CefBrowser getBrowser () {

return  this.get_browser.get_browser(this);

}

public CefFrame getFrame () {

return  this.get_frame.get_frame(this);

}

public CefV8value getGlobal () {

return  this.get_global.get_global(this);

}

public int enter () {

return  this.enter.enter(this);

}

public int exit () {

return  this.exit.exit(this);

}

public int isSame (CefV8context x1) {

return  this.is_same.is_same(this,  x1);

}

public int eval (String x1, String x2, int x3, Pointer x4, Pointer x5) {

return  this.eval.eval(this, CljCefLib.toCefString(x1), CljCefLib.toCefString(x2),  x3,  x4,  x5);

}}