// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefV8accessor extends Structure{
public CefV8accessor(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface GetFunc extends Callback {

int get(CefV8accessor x0, CefStringUtf16 x1, CefV8value x2, Pointer x3, CefStringUtf16 x4); 
}

public static interface SetFunc extends Callback {

int set(CefV8accessor x0, CefStringUtf16 x1, CefV8value x2, CefV8value x3, CefStringUtf16 x4); 
}

public CefBaseRefCounted base;

public GetFunc get;

public SetFunc set;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "get", "set");
 }

public int get (String x1, CefV8value x2, Pointer x3, String x4) {

return  this.get.get(this, CljCefLib.toCefString(x1),  x2,  x3, CljCefLib.toCefString(x4));

}

public int set (String x1, CefV8value x2, CefV8value x3, String x4) {

return  this.set.set(this, CljCefLib.toCefString(x1),  x2,  x3, CljCefLib.toCefString(x4));

}}