// AUTO GENERATED BY gen2.clj!

package com.phronemophobic.cljcef;

import com.phronemophobic.cljcef.*;

import com.sun.jna.Structure;

import com.sun.jna.Callback;

import com.sun.jna.Pointer;

import java.util.List;

import java.util.Arrays;

public class CefValue extends Structure{
public CefValue(){
base.size.setValue(this.size());

ReferenceCountImpl.track(this.getPointer());

}

public static interface IsValidFunc extends Callback {

int is_valid(CefValue x0); 
}

public static interface IsOwnedFunc extends Callback {

int is_owned(CefValue x0); 
}

public static interface IsReadOnlyFunc extends Callback {

int is_read_only(CefValue x0); 
}

public static interface IsSameFunc extends Callback {

int is_same(CefValue x0, CefValue x1); 
}

public static interface IsEqualFunc extends Callback {

int is_equal(CefValue x0, CefValue x1); 
}

public static interface CopyFunc extends Callback {

CefValue copy(CefValue x0); 
}

public static interface GetTypeFunc extends Callback {

int get_type(CefValue x0); 
}

public static interface GetBoolFunc extends Callback {

int get_bool(CefValue x0); 
}

public static interface GetIntFunc extends Callback {

int get_int(CefValue x0); 
}

public static interface GetDoubleFunc extends Callback {

double get_double(CefValue x0); 
}

public static interface GetStringFunc extends Callback {

CefStringUtf16 get_string(CefValue x0); 
}

public static interface GetBinaryFunc extends Callback {

CefBinaryValue get_binary(CefValue x0); 
}

public static interface GetDictionaryFunc extends Callback {

CefDictionaryValue get_dictionary(CefValue x0); 
}

public static interface GetListFunc extends Callback {

CefListValue get_list(CefValue x0); 
}

public static interface SetNullFunc extends Callback {

int set_null(CefValue x0); 
}

public static interface SetBoolFunc extends Callback {

int set_bool(CefValue x0, int x1); 
}

public static interface SetIntFunc extends Callback {

int set_int(CefValue x0, int x1); 
}

public static interface SetDoubleFunc extends Callback {

int set_double(CefValue x0, double x1); 
}

public static interface SetStringFunc extends Callback {

int set_string(CefValue x0, CefStringUtf16 x1); 
}

public static interface SetBinaryFunc extends Callback {

int set_binary(CefValue x0, CefBinaryValue x1); 
}

public static interface SetDictionaryFunc extends Callback {

int set_dictionary(CefValue x0, CefDictionaryValue x1); 
}

public static interface SetListFunc extends Callback {

int set_list(CefValue x0, CefListValue x1); 
}

public CefBaseRefCounted base;

public IsValidFunc is_valid;

public IsOwnedFunc is_owned;

public IsReadOnlyFunc is_read_only;

public IsSameFunc is_same;

public IsEqualFunc is_equal;

public CopyFunc copy;

public GetTypeFunc get_type;

public GetBoolFunc get_bool;

public GetIntFunc get_int;

public GetDoubleFunc get_double;

public GetStringFunc get_string;

public GetBinaryFunc get_binary;

public GetDictionaryFunc get_dictionary;

public GetListFunc get_list;

public SetNullFunc set_null;

public SetBoolFunc set_bool;

public SetIntFunc set_int;

public SetDoubleFunc set_double;

public SetStringFunc set_string;

public SetBinaryFunc set_binary;

public SetDictionaryFunc set_dictionary;

public SetListFunc set_list;

protected List getFieldOrder() {
                                            return Arrays.asList("base", "is_valid", "is_owned", "is_read_only", "is_same", "is_equal", "copy", "get_type", "get_bool", "get_int", "get_double", "get_string", "get_binary", "get_dictionary", "get_list", "set_null", "set_bool", "set_int", "set_double", "set_string", "set_binary", "set_dictionary", "set_list");
 }

public int isValid () {

return  this.is_valid.is_valid(this);

}

public int isOwned () {

return  this.is_owned.is_owned(this);

}

public int isReadOnly () {

return  this.is_read_only.is_read_only(this);

}

public int isSame (CefValue x1) {

return  this.is_same.is_same(this,  x1);

}

public int isEqual (CefValue x1) {

return  this.is_equal.is_equal(this,  x1);

}

public CefValue copy () {

return  this.copy.copy(this);

}

public int getType () {

return  this.get_type.get_type(this);

}

public int getBool () {

return  this.get_bool.get_bool(this);

}

public int getInt () {

return  this.get_int.get_int(this);

}

public double getDouble () {

return  this.get_double.get_double(this);

}

public CefStringUtf16 getString () {

return  this.get_string.get_string(this);

}

public CefBinaryValue getBinary () {

return  this.get_binary.get_binary(this);

}

public CefDictionaryValue getDictionary () {

return  this.get_dictionary.get_dictionary(this);

}

public CefListValue getList () {

return  this.get_list.get_list(this);

}

public int setNull () {

return  this.set_null.set_null(this);

}

public int setBool (int x1) {

return  this.set_bool.set_bool(this,  x1);

}

public int setInt (int x1) {

return  this.set_int.set_int(this,  x1);

}

public int setDouble (double x1) {

return  this.set_double.set_double(this,  x1);

}

public int setString (String x1) {

return  this.set_string.set_string(this, CljCefLib.toCefString(x1));

}

public int setBinary (CefBinaryValue x1) {

return  this.set_binary.set_binary(this,  x1);

}

public int setDictionary (CefDictionaryValue x1) {

return  this.set_dictionary.set_dictionary(this,  x1);

}

public int setList (CefListValue x1) {

return  this.set_list.set_list(this,  x1);

}}