name: Clojars deploy
on:
    workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - uses: actions/checkout@v2
    - name: Setup Clojure
      # You may pin to the exact commit or the version.
      # uses: DeLaGuardo/setup-clojure@5042876523f30f5efcf1d6feaa48bd1498d7814f
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        # Clojure CLI version to make available on the path.
        cli: 1.11.0.1100

    - name: Install dependencies
      run: clojure -P

    - name: Deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: clojure -T:build deploy


